version: '3.4'

services:
  hamasasafaris:
    image: hamasasafaris
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001
