version: '3.4'

services:
  hamasasafaris:
    image: hamasasafaris
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3002:3002
      - 9229:9229
    command: ["NODE_ENV=production","node", "--inspect=0.0.0.0:9229", "server.js"]
